### ISSUE TITLE
Error when visiting the website served by web container

### ISSUE THREAD

**Issue by Kunmeer-SyedMohamedHyder** [jpetazzo/wordsmith#11]
- I was practicing Exercise 2. I was trying to do a docker compose. The docker compose worked well and then I tried to visit the website being served by the **web** container.
- I just see a website with the blocks getting displayed without any text in them.
- I followed all the same steps as you showed in the tutorial.
- When I came back and looked at the logs of the **web** container, I saw the following errors

![image](https://user-images.githubusercontent.com/114393935/215542981-4800658b-cf78-4230-98c1-b0cfa0e583c5.png)

- This is how the website looks

![Screenshot (23)](https://user-images.githubusercontent.com/114393935/215543701-612865ae-0925-42e1-9be7-3bddf2f99c88.png)

**Comment by jpetazzo** [comment]
Hi,

If you see bricks without words in them, it typically means that the `web` container wasn't able to connect to the `words` container. 

That being said, the error messages that you have in the `web` container output (related to `127.0.0.11:53`) indicate DNS issues... That's unfortunately outside of the scope of wordsmith. It looks like you're using Docker Desktop; you can try to restart it and see and the problem persists?

**Comment by Kunmeer-SyedMohamedHyder** [comment]
Yes, I am using `Docker Desktop`. Whenever we use the Default network for the containers, I see the DNS doesn't resolve them based on their network aliases. 
May be because of that we have this issue. I was not able to resolve it but closing this issue as it would work on a linux environment.

**Comment by jpetazzo** [comment]
Ohhh, ok!

Then it makes sense - the DNS resolver only works for custom networks, not for the default one.

I.e. if you `docker run --net-alias hello alpine`, it doesn't create a DNS alias. You need to specify `--net mycustomnetwork`.
